name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

template: |
  ## What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/stephenkelzer/snake/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION