[package]
name = "snake"
version = "0.0.0"            # this get's updated automatically by our deployment GitHub Action
edition = "2021"
authors = ["Stephen Kelzer"]

[dependencies]
yew = "0.19.3"
getrandom = { version = "0.2.7", features = ["js"] }
rand = "0.8.5"
