[package]
name = "ui"
version = "0.0.0"            # this get's updated automatically by our deployment GitHub Action
edition = "2021"
authors = ["Stephen Kelzer"]

[dependencies]
yew = "0.19.3"
gloo = "0.8.0"
game = { path = "../../src/game" }
