name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  release:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$' # semver
    types:
      - published

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages-deploy"
  cancel-in-progress: true

jobs:

  build-artifact:

    runs-on: ubuntu-latest

    steps:

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update TOML File Version
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: ${{ github.ref_name }} # tag name (which is the semver version)

      - name: Compile WebAssembly Package
        run: wasm-pack build --target web

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
  
  deploy-to-github-pages:

    needs: build-artifact

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1