name: Deploy to GitHub Pages

on:
  release:
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$' # semver
    types:
      - published

env:
  CARGO_TERM_COLOR: always
  GITHUB_PAGES_VIRTUAL_DIRECTORY: snake

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "gh-pages-deploy"
  cancel-in-progress: true

jobs:

  build-artifact:

    runs-on: ubuntu-latest

    steps:

      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Download WASM Target
        run: rustup target add wasm32-unknown-unknown

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update TOML File Version
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: ${{ github.ref_name }}

      - name: Build
        run: trunk build --release --public-url="snake" # Needed for GitHub Pages to work

      - name: Add GitHub Pages 404 Page
        run: echo '<script>window.location.href="/snake";</script>' > dist/404.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
  
  deploy-to-github-pages:

    needs: build-artifact

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1