name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  release-drafter:

    name: Run Release Drafter

    runs-on: ubuntu-latest

    steps:

      - uses: release-drafter/release-drafter@v5
        env:
          config-name: release-drafter-template.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}